[build]
  base = "/"
  publish = "public/"
  command = "yarn build"

[template.environment]
  GATSBY_MOLTIN_CLIENT_ID = "hp5yFSsxU2isNXxrzDslVwmEqdp3ufWPHddAiyoLkD"
  GATSBY_STRIPE_PUBLISHABLE_KEY = "pk_test_51HoUs1DgpcrSlzUG2wWrQpwL3GgSMpeWd4AVVN34bH1ufYnldiVUixLHPiMSTb61jIToMkFqhLMTLgCFUprLMBy900pJvgFMzc"
  GATSBY_ALGOLIA_PLACES_APP_ID = "Your Algolia places app ID"
  GATSBY_ALGOLIA_PLACES_API_KEY = "Your Algolia places API key"
  GATSBY_ALGOLIA_INDEX_NAME = "gatsby_ecommerce_demo"
  ALGOLIA_ADMIN_KEY ="a35ed1bd5f905941dc64fd819a322239"
  GATSBY_ALGOLIA_API_KEY ="67c10ff2082300c3081a061095303a65"
  GATSBY_ALGOLIA_APP_ID ="KFDHEJHC8D"
  GATSBY_ITEMS_PER_PAGE = "9"
